# this is a config file for gitpod setup, ignore if you are running samples locally
# See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

tasks:
  - name: Temporal Server
    init: docker-compose pull
    command: docker-compose up
  - name: Readiness monitor
    command: |
      echo "Waiting for tctl container"
      while echo -n "." && sleep 1
      do
        docker container ls -a --filter "name=temporal-admin-tools" --filter "status=running" | grep -q 'temporal-admin-tools' &&
        echo "ready" &&
        break
      done

      echo "Waiting for temporal server"
      while echo -n "." && sleep 1
      do
        docker exec temporal-admin-tools tctl cluster health | grep -q 'SERVING' &&
        echo "ready" &&
        gp sync-done serving &&
        break
      done
  - name: Run Hello World Worker
    init: |
      gp sync-await serving
    command: |
      go run ./helloworld/worker/main.go
  - name: Run Hello World Workflow
    init: |
      gp sync-await serving
    command: |
      go run ./helloworld/starter/main.go
    openMode: split-right
  - name: tctl playground
    init: |
      gp sync-await serving
    command: |
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v"
  - name: Temporal Web
    init: |
      gp sync-await serving
    command: |
      gp preview http://localhost:8088
ports:
  - port: 5432 # postgres
    onOpen: ignore
  - port: 9200 # elasticsearch
    onOpen: ignore
  - port: 7233 # temporal server
    onOpen: ignore
  - port: 8088 # temporal web
    onOpen: ignore
    visibility: public
# notes for future temporalite usage
#  - name: Temporalite
#    init: go install github.com/DataDog/temporalite/cmd/temporalite@latest
#    command: temporalite start --namespace default -f my-test.db
# separate temporal web
#      docker run -t -i -p 8088:8088 -e TEMPORAL_GRPC_ENDPOINT=temporal:7233 temporalio/web:1.12.0 # this does not work yet :(
